services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:${PORT:-8000}"
    volumes:
      - .:/app
    command: poetry run python apps/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DEBUG=True
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432