# Generated by Django 5.1.3 on 2024-11-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Expense",
            new_name="Expenses",
        ),
    ]
