# Generated by Django 5.1.3 on 2024-12-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_expense_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
